name: mobile_inventory_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.23
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  intl: ^0.20.0
  firebase_auth: 5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.2.5
  latlng: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
