// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA785NjQUvMbpvZ9_NGtTwZtnFbwdm79FA',
    appId: '1:444571638006:web:39ca45f9a55bdad182b4d7',
    messagingSenderId: '444571638006',
    projectId: 'fir-auth-65c7e',
    authDomain: 'fir-auth-65c7e.firebaseapp.com',
    storageBucket: 'fir-auth-65c7e.firebasestorage.app',
    measurementId: 'G-1SLZYZKKGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6A-LEIEyDny_Sc3xD3OBC3EFO6kd-ME',
    appId: '1:444571638006:android:ad3c442b7749baef82b4d7',
    messagingSenderId: '444571638006',
    projectId: 'fir-auth-65c7e',
    storageBucket: 'fir-auth-65c7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe2AT3aofuGpP8sTzNDxVDL3Y-lkTZ_6M',
    appId: '1:444571638006:ios:0be321fb51f503b282b4d7',
    messagingSenderId: '444571638006',
    projectId: 'fir-auth-65c7e',
    storageBucket: 'fir-auth-65c7e.firebasestorage.app',
    iosBundleId: 'com.example.mobileInventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe2AT3aofuGpP8sTzNDxVDL3Y-lkTZ_6M',
    appId: '1:444571638006:ios:0be321fb51f503b282b4d7',
    messagingSenderId: '444571638006',
    projectId: 'fir-auth-65c7e',
    storageBucket: 'fir-auth-65c7e.firebasestorage.app',
    iosBundleId: 'com.example.mobileInventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA785NjQUvMbpvZ9_NGtTwZtnFbwdm79FA',
    appId: '1:444571638006:web:f436f7ce496cb11e82b4d7',
    messagingSenderId: '444571638006',
    projectId: 'fir-auth-65c7e',
    authDomain: 'fir-auth-65c7e.firebaseapp.com',
    storageBucket: 'fir-auth-65c7e.firebasestorage.app',
    measurementId: 'G-PV9C2HS4TQ',
  );

}